### ISSUE TITLE
NPE I assume from the facilities to metro changes, but haven't dug into it yet

### ISSUE THREAD

**Issue by phillipbroberts** [equinix-labs/metal-sweeper-action#16]
WARNING: 2023/06/19 15:56:41 main.go:45: Could not list devices GET https://api.equinix.com/metal/v1/projects/devices?include=facility: 404 Not found 
WARNING: 2023/06/19 15:56:41 main.go:58: Could not list vlans GET https://api.equinix.com/metal/v1/projects/virtual-networks: 404 Not found 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x672ef1]

goroutine 1 [running]:
main.main()
	/code/main.go:61 +0x3f1

**Comment by ctreatma** [comment]
Based on the request URLs in the warning logs, it looks like the project ID is not set; the logs indicate that requests are being sent to `https://api.equinix.com/metal/v1/projects/virtual-networks` but the URL should be in the format `https://api.equinix.com/metal/v1/projects/<projectID>/virtual-networks`.  Is the project ID hard-coded in your actions workflow or is it coming in from a previous step?

**Comment by phillipbroberts** [comment]
You are correct. After fixing another bug in my actions file this resolved. My apologies.
